name: Github Action for LaTeX
description: GitHub Action to compile LaTeX documents
author: Cheng XU
inputs:
  root_file:
    description: The root LaTeX file to be compiled
    required: true
  token:
    description: "github token. this is require when comment is true."
    default: ""
    required: true
  event_path:
    description: "github event_path. this is require when comment is true."
    default: ""
    required: true
  working_directory:
    description: The working directory for texliveonfly to be invoked
  compiler:
    description: LaTeX engine to be used by texliveonfly
    default: latexmk
  args:
    description: Extra arguments to be passed to texliveonfly
    default: "-pdf -file-line-error -interaction=nonstopmode"
  extra_packages:
    description: Install extra packages by tlmgr
  extra_system_packages:
    description: Install extra packages by apk
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.root_file }}
    - ${{ inputs.token }}
    - ${{ inputs.event_path }}
    #- ${{ inputs.args }}
    #- ${{ inputs.extra_packages }}
    #- ${{ inputs.extra_system_packages }}
branding:
  icon: book
  color: blue
