name: Github Action for LaTeX
description: GitHub Action to compile LaTeX documents
author: Cheng XU
inputs:
  root_file:
    description: The root LaTeX file to be compiled
    required: true
  token:
    description: "github token. this is require when comment is true."
    default: ""
    required: true
  event_path:
    description: "github event_path. this is require when comment is true."
    default: ""
    required: true
  repo:
    description: "github repository. this is require when comment is true."
    default: ""
    required: true
  tags:
    description: "github event_path. this is require when comment is true."
    default: ""
    required: true
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.root_file }}
    - ${{ inputs.token }}
    - ${{ inputs.event_path }}
    - ${{ inputs.repo}}
    - ${{ inputs.tags }}
branding:
  icon: book
  color: blue
